Standalone Search Widget
GovWizely/zAPIness-search-widget pull request #1
Opened 2017-04-17 09:03 UTC by yih-en

### Basic Info
Search Widget that allow user to search based on zAPIness endpoints

[Live Demo](http://zapi-widget.herokuapp.com/)

<img width="638" alt="screen shot 2017-04-17 at 4 13 43 pm" src="https://cloud.githubusercontent.com/assets/21019282/25083294/dd33c8d2-2388-11e7-9cb7-18e6a25736b4.png">

___

### Basic Usage

Load Search Widget in any webpage by embedding the following javascripts:

```javascript
<script type="text/javascript">
  var script = document.createElement('script');
  script.src = "https://govwizely.github.io/zAPIness-search-widget/static/js/main.fdfe92ee.js";
  document.getElementsByTagName('head')[0].appendChild(script);

  window.onload = function() {
    //Create div element
    var div = document.createElement("div");
    div.setAttribute("id", "root");
    document.body.appendChild(div);

    // Initiate the search widget with endpoint
    SearchWidget.new({
      endpoint: "[zAPIness endpoint]"
    });
  }
</script>
```
___

### Stacks Used

* React + REDUX
* [Immutable-js](https://facebook.github.io/immutable-js/) - For persistent immutable data
* [Radium](http://formidable.com/open-source/radium/) - For inline css stylings
* [Redux Form](http://redux-form.com/6.6.3/)
* Webpack 
* Babel
* Eslint - based on the latest airbnb config
* Jest - For testing
* [react-script](https://www.npmjs.com/package/react-scripts) - To build production based JS files
___

### Basic Workflow

When Search Widget is initialized, the endpoint will be stored as the main endpoint in ```actions/api.js```. Any requests will be made according to this endpoint after initialization. Redux store will be initialized with the following initial states:

```
const initialState = Map({
  categories: [],
  keyword: '',
  offset: 0,
  pageNum: 1,
  filters: [],
  data: undefined,
  error: []
})
```

* ___categories___: 
	* This field will be populated right before the React App is mounted.
	* It grabs values from data.aggregations passed from the endpoint.
	* It is used in creating filters in the search widget
* ___keyword___: 
	* Store user input.
	* ```GET``` requests will be made when user key in the search input field. The onchange event is debounced to avoid redundant requests to backend server. Refer to ```src/components/Form.js:L44```
* ___offset___:
	* Used in Pagination that determine the data offset according to the selected page number
	* This field is used in building params in ```GET``` request. To access the info in subsequent page, we need to pass in ```?offset=[num]```

* ___pageNum___:
	* Store user input on page number
	* Important in building params 
* ___filters___:
	* Used in query builder
	* Ideally, the structure of search query should be:
	```
    params = {
       "q": "office",
       "offset": 0,
       "filter": {
         agency: ['ausaid', 'australian national audit office (anao)'],
         category: ['architectural engineering']
       }
     }
     ```
     * The type and values of the filters are dictated by user input

* ___data___:
	* Result returned by the endpoint

* ___error___:
	* Store any errors returned by the endpoint

2017-04-19 12:25 UTC, viclim commented on src/components/Drawer.js
> +        href="{undefined}"
@yih-en I have never seen this before. Is it different from `javascript:void(0)`?

2017-04-19 12:30 UTC, viclim commented
@yih-en 
A search seems to hit the API multiple times. [screenshot](http://recordit.co/h1r5xfI613)

2017-04-20 02:39 UTC, yih-en commented
@viclim, it's expected to have 2 API calls in your case. The first time the widget loads, an API call will be made to retrieve all the filters available for the dropdown in advanced search. Then, when you key in the input, another API call will be made once you stop typing/interacting with the search bar.

2017-04-20 02:41 UTC, yih-en commented on src/components/Drawer.js
> +        href="{undefined}"
This is related to the ESLint: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/href-no-hash.md. But I think using javascript:void(0) in href is better. Let me fix that :)

2017-04-20 06:49 UTC, viclim commented
That makes sense.

2017-04-24 04:46 UTC, blackcofla requested changes

2017-04-24 04:46 UTC, blackcofla commented on src/actions/__tests__/range-test.js
> +  it('sets initial to 2 if current number is 1', () => {
Seems like at the end, this test exercise the same flow than first test?

2017-04-24 04:46 UTC, blackcofla commented on src/actions/range.js
> +const getRange = (activePage, totalPage, totalNumButton) => {
What about validating that the 3 arguments are bigger than 0?

2017-04-24 04:46 UTC, blackcofla commented on src/components/Pagination.js
> +            className="previous-page"
This style shouldn't be "next-page"?

2017-04-24 04:46 UTC, blackcofla commented on src/components/__tests__/Filter-test.js
> +describe('components/Filter', () => {
Shouldn't we test if the handlers are called properly like in previous test?

2017-04-24 04:46 UTC, blackcofla commented on src/components/__tests__/Pagination-test.js
> +          <li><a>« Prev</a></li>
I'm confused, shouldn't the previous be rendered with a less than sign like:

< Prev

2017-04-25 07:13 UTC, yih-en commented on src/components/__tests__/Filter-test.js
> +describe('components/Filter', () => {
Yeah. Let me add that.

2017-04-25 07:14 UTC, yih-en commented on src/components/Pagination.js
> +            className="previous-page"
My bad. As we are using inline-style, the className doesn't matter in this case. ```className``` are mainly used in tests.

2017-04-25 07:15 UTC, yih-en commented on src/actions/range.js
> +const getRange = (activePage, totalPage, totalNumButton) => {
sure

2017-04-25 07:19 UTC, yih-en commented on src/actions/__tests__/range-test.js
> +  it('sets initial to 2 if current number is 1', () => {
Not quite the same. The first one test the scenario when the total page returned is less than our preset range, let's say, 3. Then, it should return the range between the current page and last page.

2017-04-27 02:54 UTC, merged